baseURL                          = "/"  # Your domain name. Must end with "/"
theme = "hugo-theme-introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                       # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                       # https://gohugo.io/templates/internal/#google-analytics
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "youremail@email.com"   # E-mail address for contact section
    #customCSS                    = "custom-style.css"      # Include custom css files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "large"                 # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "America/Los_Angeles"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        googlePlus               = true
        pinterest                = true

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Find icon names here: https://fontawesome.com/cheatsheet/
    [[params.social]]
        url   = "https://twitter.com/hashtag/adalovelace"
        icon  = "twitter"
    [[params.social]]
        url   = "https://octodex.github.com/mona-lovelace"
        icon  = "github"
    [[params.social]]
        url   = "https://github.com/apreshill/ada-blog"
        icon  = "r-project"
    [[params.social]]
        url   = "https://en.wikipedia.org/wiki/Ada_Lovelace"
        icon  = "wikipedia-w"

# If you don't want to use the default menu, you can define one by yourself
# [[menu.main]]
#     name    = "Home"
#     url     = "/"
#     weight  = 0
# [[menu.main]]
#     name    = "Blog"
#     url     = "/blog/"
#     weight  = 1

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"


[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "Ada Lovelace"
        [languages.en.params]
            description  = "A blog for Ada"   # Max 160 characters show in search results
            # footerText   = ""                      # Text to override default footer text (markdown allowed)


