---
title: take a sad plot and make it better- take 2
author: Alison Hill
date: '2018-06-13'
slug: better-2
categories: []
tags: []
description: Desc
hacker_news_id: ''
lobsters_id: ''
meta_img: /images/image.jpg
---

```{r include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
  comment = NA, dpi = 300,
  fig.align = "center", out.width = "70%", cache = FALSE)
```

# Packages

```{r}
library(tidyverse)
library(viridis) # colors!
library(beyonce) # colors!!
library(extrafont) # fonts!
```

# The data

Here I read in a local data file using this advice:
https://blogdown-demo.rbind.io/2018/02/27/r-file-paths/#place-file-in-your-staticdata-folder

```{r}
ratings <- read_csv(here::here("static", "data", "episodes.csv"),
                           na = c("", "NA", "N/A"),
                         col_types = cols(
                           viewers_7day = col_number(),
                           series = col_factor(levels = NULL)
                         )) 
```

## Recipe 2: Lollipop Plot

```{r}
ratings_bonanza2 <- ratings %>% 
  group_by(series) %>% 
  mutate(series_avg = mean(viewers_7day, na.rm = TRUE),
         diff_avg = viewers_7day - series_avg)%>% 
  filter(max(episode) == 10) %>% 
  mutate(episode = as.factor(episode)) %>% 
  select(episode, viewers_7day, series, diff_avg, series_avg)

ggplot(ratings_bonanza2, aes(x = episode, 
                            y = viewers_7day,
                            color = diff_avg)) +
  geom_hline(aes(yintercept = series_avg), alpha = .5) +
  geom_point() +
  geom_segment(aes(xend = episode, yend = series_avg)) +
  facet_wrap(~series) +
  scale_color_viridis(option="plasma", begin = 0, 
                      end = .8, guide = FALSE) +
  theme_minimal() +
  theme(text = element_text(family = "Lato")) +
  ggtitle("Great British Bake Off Finales Get the Most Viewers",
          subtitle = "Way Higher than Series Average (for Series with 10 episodes)")
```

